[package]
name = "chess-results-client"
version = "0.1.0"
edition = "2021"

[lib]
name = "chess_results_client"
path = "src/lib.rs"

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "rustls-tls"], default-features = false }
regex = "1"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
