// GENERATED by scripts/extract-piece-set.mjs — do not edit by hand.
//
// The pieces the app draws on its own board, as fill-and-stroke instructions
// for the PDF export: Colin M.L. Burnett's set, as shipped by react-chessboard.
// Licensed by its author under the BSD licence (also GPLv2+ and GFDL); see
// src/assets/pieces/LICENSE.txt. Coordinates are on a 45-unit square with
// y pointing down, the way the SVG has them.

export const PIECE_SET_SIZE = 45;

export type PieceOp =
  | { kind: "path"; d: string; fill: string | null; stroke: string | null; strokeWidth: number; cap: "butt" | "round" | "square" }
  | { kind: "circle"; cx: number; cy: number; r: number; fill: string | null; stroke: string | null; strokeWidth: number; cap: "butt" | "round" | "square" };

/** Upper case is White, lower case Black, as in a FEN. */
export const PIECE_SET: Record<string, PieceOp[]> = {
 K: [
  {
   kind: "path",
   d: "M22.5 11.63 L22.5 6",
   fill: null,
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M20 8 L25 8",
   fill: null,
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M22.5 25 C22.5 25 27 17.5 25.5 14.5 C25.5 14.5 24.5 12 22.5 12 C20.5 12 19.5 14.5 19.5 14.5 C18 17.5 22.5 25 22.5 25",
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M12.5 37 C18 40.5 27 40.5 32.5 37 L32.5 30 C32.5 30 41.5 25.5 38.5 19.5 C34.5 13 25 16 22.5 23.5 L22.5 27 L22.5 23.5 C20 16 10.5 13 6.5 19.5 C3.5 25.5 12.5 30 12.5 30 L12.5 37",
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M12.5 30 C18 27 27 27 32.5 30",
   fill: null,
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M12.5 33.5 C18 30.5 27 30.5 32.5 33.5",
   fill: null,
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M12.5 37 C18 34 27 34 32.5 37",
   fill: null,
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  }
 ],
 Q: [
  {
   kind: "path",
   d: "M9 26 C17.5 24.5 30 24.5 36 26 L38.5 13.5 L31 25 L30.7 10.9 L25.5 24.5 L22.5 10 L19.5 24.5 L14.3 10.9 L14 25 L6.5 13.5 L9 26 Z",
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M9 26 C9 28 10.5 28 11.5 30 C12.5 31.5 12.5 31 12 33.5 C10.5 34.5 11 36 11 36 C9.5 37.5 11 38.5 11 38.5 C17.5 39.5 27.5 39.5 34 38.5 C34 38.5 35.5 37.5 34 36 C34 36 34.5 34.5 33 33.5 C32.5 31 32.5 31.5 33.5 30 C34.5 28 36 28 36 26 C27.5 24.5 17.5 24.5 9 26 Z",
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M11.5 30 C15 29 30 29 33.5 30",
   fill: null,
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M12 33.5 C18 32.5 27 32.5 33 33.5",
   fill: null,
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "circle",
   cx: 6,
   cy: 12,
   r: 2,
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "circle",
   cx: 14,
   cy: 9,
   r: 2,
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "circle",
   cx: 22.5,
   cy: 8,
   r: 2,
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "circle",
   cx: 31,
   cy: 9,
   r: 2,
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "circle",
   cx: 39,
   cy: 12,
   r: 2,
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  }
 ],
 R: [
  {
   kind: "path",
   d: "M9 39 L36 39 L36 36 L9 36 L9 39 Z",
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M12 36 L12 32 L33 32 L33 36 L12 36 Z",
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M11 14 L11 9 L15 9 L15 11 L20 11 L20 9 L25 9 L25 11 L30 11 L30 9 L34 9 L34 14",
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M34 14 L31 17 L14 17 L11 14",
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M31 17 L31 29.5 L14 29.5 L14 17",
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M31 29.5 L32.5 32 L12.5 32 L14 29.5",
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M11 14 L34 14",
   fill: null,
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  }
 ],
 B: [
  {
   kind: "path",
   d: "M9 36 C12.39 35.03 19.11 36.43 22.5 34 C25.89 36.43 32.61 35.03 36 36 C36 36 37.65 36.54 39 38 C38.32 38.97 37.35 38.99 36 38.5 C32.61 37.53 25.89 38.96 22.5 37.5 C19.11 38.96 12.39 37.53 9 38.5 C7.65 38.99 6.68 38.97 6 38 C7.35 36.54 9 36 9 36 Z",
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M15 32 C17.5 34.5 27.5 34.5 30 32 C30.5 30.5 30 30 30 30 C30 27.5 27.5 26 27.5 26 C33 24.5 33.5 14.5 22.5 10.5 C11.5 14.5 12 24.5 17.5 26 C17.5 26 15 27.5 15 30 C15 30 14.5 30.5 15 32 Z",
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M25 8 C25 9.381 23.881 10.5 22.5 10.5 C21.119 10.5 20 9.381 20 8 C20 6.619 21.119 5.5 22.5 5.5 C23.881 5.5 25 6.619 25 8 Z",
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M17.5 26 L27.5 26 M15 30 L30 30 M22.5 15.5 L22.5 20.5 M20 18 L25 18",
   fill: null,
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  }
 ],
 N: [
  {
   kind: "path",
   d: "M22 10 C32.5 11 38.5 18 38 39 L15 39 C15 30 25 32.5 23 18",
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M24 18 C24.38 20.91 18.45 25.37 16 27 C13 29 13.18 31.34 11 31 C9.958 30.06 12.41 27.96 11 28 C10 28 11.19 29.23 10 30 C9 30 5.997 31 6 26 C6 24 12 14 12 14 C12 14 13.89 12.1 14 10.5 C13.27 9.506 13.5 8.5 13.5 7.5 C14.5 6.5 16.5 10 16.5 10 L18.5 10 C18.5 10 19.28 8.008 21 7 C22 7 22 10 22 10",
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M9.5 25.5 C9.5 25.776 9.276 26 9 26 C8.724 26 8.5 25.776 8.5 25.5 C8.5 25.224 8.724 25 9 25 C9.276 25 9.5 25.224 9.5 25.5 Z",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M14.933 15.75 C14.519 16.467 13.989 16.937 13.75 16.799 C13.511 16.661 13.653 15.967 14.067 15.25 C14.481 14.533 15.011 14.063 15.25 14.201 C15.489 14.339 15.347 15.033 14.933 15.75 Z",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.499966999636992,
   cap: "round"
  }
 ],
 P: [
  {
   kind: "path",
   d: "M22.5 9 C20.29 9 18.5 10.79 18.5 13 C18.5 13.89 18.79 14.71 19.28 15.38 C17.33 16.5 16 18.59 16 21 C16 23.03 16.94 24.84 18.41 26.03 C15.41 27.09 11 31.58 11 39.5 L34 39.5 C34 31.58 29.59 27.09 26.59 26.03 C28.06 24.84 29 23.03 29 21 C29 18.59 27.67 16.5 25.72 15.38 C26.21 14.71 26.5 13.89 26.5 13 C26.5 10.79 24.71 9 22.5 9 Z",
   fill: "#ffffff",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  }
 ],
 k: [
  {
   kind: "path",
   d: "M22.5 11.63 L22.5 6",
   fill: null,
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M22.5 25 C22.5 25 27 17.5 25.5 14.5 C25.5 14.5 24.5 12 22.5 12 C20.5 12 19.5 14.5 19.5 14.5 C18 17.5 22.5 25 22.5 25",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M12.5 37 C18 40.5 27 40.5 32.5 37 L32.5 30 C32.5 30 41.5 25.5 38.5 19.5 C34.5 13 25 16 22.5 23.5 L22.5 27 L22.5 23.5 C20 16 10.5 13 6.5 19.5 C3.5 25.5 12.5 30 12.5 30 L12.5 37",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M20 8 L25 8",
   fill: null,
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M32 29.5 C32 29.5 40.5 25.5 38.03 19.85 C34.15 14 25 18 22.5 24.5 L22.5 26.6 L22.5 24.5 C20 18 10.85 14 6.97 19.85 C4.5 25.5 13 29.5 13 29.5",
   fill: null,
   stroke: "#ffffff",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M12.5 30 C18 27 27 27 32.5 30 M12.5 33.5 C18 30.5 27 30.5 32.5 33.5 M12.5 37 C18 34 27 34 32.5 37",
   fill: null,
   stroke: "#ffffff",
   strokeWidth: 1.5,
   cap: "round"
  }
 ],
 q: [
  {
   kind: "path",
   d: "M9 26 C17.5 24.5 30 24.5 36 26 L38.5 13.5 L31 25 L30.7 10.9 L25.5 24.5 L22.5 10 L19.5 24.5 L14.3 10.9 L14 25 L6.5 13.5 L9 26 Z",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M9 26 C9 28 10.5 28 11.5 30 C12.5 31.5 12.5 31 12 33.5 C10.5 34.5 11 36 11 36 C9.5 37.5 11 38.5 11 38.5 C17.5 39.5 27.5 39.5 34 38.5 C34 38.5 35.5 37.5 34 36 C34 36 34.5 34.5 33 33.5 C32.5 31 32.5 31.5 33.5 30 C34.5 28 36 28 36 26 C27.5 24.5 17.5 24.5 9 26 Z",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M11.5 30 C15 29 30 29 33.5 30",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M12 33.5 C18 32.5 27 32.5 33 33.5",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "circle",
   cx: 6,
   cy: 12,
   r: 2,
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "circle",
   cx: 14,
   cy: 9,
   r: 2,
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "circle",
   cx: 22.5,
   cy: 8,
   r: 2,
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "circle",
   cx: 31,
   cy: 9,
   r: 2,
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "circle",
   cx: 39,
   cy: 12,
   r: 2,
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M11 38.5 C18.448 41.091 26.552 41.091 34 38.5",
   fill: null,
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M11 29 C18.448 26.409 26.552 26.409 34 29",
   fill: null,
   stroke: "#ffffff",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M12.5 31.5 L32.5 31.5",
   fill: null,
   stroke: "#ffffff",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M11.5 34.5 C18.643 36.865 26.357 36.865 33.5 34.5",
   fill: null,
   stroke: "#ffffff",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M10.5 37.5 C18.25 40.329 26.75 40.329 34.5 37.5",
   fill: null,
   stroke: "#ffffff",
   strokeWidth: 1.5,
   cap: "round"
  }
 ],
 r: [
  {
   kind: "path",
   d: "M9 39 L36 39 L36 36 L9 36 L9 39 Z",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M12.5 32 L14 29.5 L31 29.5 L32.5 32 L12.5 32 Z",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M12 36 L12 32 L33 32 L33 36 L12 36 Z",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M14 29.5 L14 16.5 L31 16.5 L31 29.5 L14 29.5 Z",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M14 16.5 L11 14 L34 14 L31 16.5 L14 16.5 Z",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M11 14 L11 9 L15 9 L15 11 L20 11 L20 9 L25 9 L25 11 L30 11 L30 9 L34 9 L34 14 L11 14 Z",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M12 35.5 L33 35.5 L33 35.5",
   fill: null,
   stroke: "#ffffff",
   strokeWidth: 1,
   cap: "round"
  },
  {
   kind: "path",
   d: "M13 31.5 L32 31.5",
   fill: null,
   stroke: "#ffffff",
   strokeWidth: 1,
   cap: "round"
  },
  {
   kind: "path",
   d: "M14 29.5 L31 29.5",
   fill: null,
   stroke: "#ffffff",
   strokeWidth: 1,
   cap: "round"
  },
  {
   kind: "path",
   d: "M14 16.5 L31 16.5",
   fill: null,
   stroke: "#ffffff",
   strokeWidth: 1,
   cap: "round"
  },
  {
   kind: "path",
   d: "M11 14 L34 14",
   fill: null,
   stroke: "#ffffff",
   strokeWidth: 1,
   cap: "round"
  }
 ],
 b: [
  {
   kind: "path",
   d: "M9 36 C12.39 35.03 19.11 36.43 22.5 34 C25.89 36.43 32.61 35.03 36 36 C36 36 37.65 36.54 39 38 C38.32 38.97 37.35 38.99 36 38.5 C32.61 37.53 25.89 38.96 22.5 37.5 C19.11 38.96 12.39 37.53 9 38.5 C7.65 38.99 6.68 38.97 6 38 C7.35 36.54 9 36 9 36 Z",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M15 32 C17.5 34.5 27.5 34.5 30 32 C30.5 30.5 30 30 30 30 C30 27.5 27.5 26 27.5 26 C33 24.5 33.5 14.5 22.5 10.5 C11.5 14.5 12 24.5 17.5 26 C17.5 26 15 27.5 15 30 C15 30 14.5 30.5 15 32 Z",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M25 8 C25 9.381 23.881 10.5 22.5 10.5 C21.119 10.5 20 9.381 20 8 C20 6.619 21.119 5.5 22.5 5.5 C23.881 5.5 25 6.619 25 8 Z",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "butt"
  },
  {
   kind: "path",
   d: "M17.5 26 L27.5 26 M15 30 L30 30 M22.5 15.5 L22.5 20.5 M20 18 L25 18",
   fill: null,
   stroke: "#ffffff",
   strokeWidth: 1.5,
   cap: "round"
  }
 ],
 n: [
  {
   kind: "path",
   d: "M22 10 C32.5 11 38.5 18 38 39 L15 39 C15 30 25 32.5 23 18",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M24 18 C24.38 20.91 18.45 25.37 16 27 C13 29 13.18 31.34 11 31 C9.958 30.06 12.41 27.96 11 28 C10 28 11.19 29.23 10 30 C9 30 5.997 31 6 26 C6 24 12 14 12 14 C12 14 13.89 12.1 14 10.5 C13.27 9.506 13.5 8.5 13.5 7.5 C14.5 6.5 16.5 10 16.5 10 L18.5 10 C18.5 10 19.28 8.008 21 7 C22 7 22 10 22 10",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M9.5 25.5 C9.5 25.776 9.276 26 9 26 C8.724 26 8.5 25.776 8.5 25.5 C8.5 25.224 8.724 25 9 25 C9.276 25 9.5 25.224 9.5 25.5 Z",
   fill: "#ffffff",
   stroke: "#ffffff",
   strokeWidth: 1.5,
   cap: "round"
  },
  {
   kind: "path",
   d: "M14.933 15.75 C14.519 16.467 13.989 16.937 13.75 16.799 C13.511 16.661 13.653 15.967 14.067 15.25 C14.481 14.533 15.011 14.063 15.25 14.201 C15.489 14.339 15.347 15.033 14.933 15.75 Z",
   fill: "#ffffff",
   stroke: "#ffffff",
   strokeWidth: 1.499966999636992,
   cap: "round"
  },
  {
   kind: "path",
   d: "M24.55 10.4 L24.1 11.85 L24.6 12 C27.75 13 30.25 14.49 32.5 18.75 C34.75 23.01 35.75 29.06 35.25 39 L35.2 39.5 L37.45 39.5 L37.5 39 C38 28.94 36.62 22.15 34.25 17.66 C31.88 13.17 28.46 11.02 25.06 10.5 L24.55 10.4 Z",
   fill: "#ffffff",
   stroke: null,
   strokeWidth: 1.5,
   cap: "round"
  }
 ],
 p: [
  {
   kind: "path",
   d: "M22.5 9 C20.29 9 18.5 10.79 18.5 13 C18.5 13.89 18.79 14.71 19.28 15.38 C17.33 16.5 16 18.59 16 21 C16 23.03 16.94 24.84 18.41 26.03 C15.41 27.09 11 31.58 11 39.5 L34 39.5 C34 31.58 29.59 27.09 26.59 26.03 C28.06 24.84 29 23.03 29 21 C29 18.59 27.67 16.5 25.72 15.38 C26.21 14.71 26.5 13.89 26.5 13 C26.5 10.79 24.71 9 22.5 9 Z",
   fill: "#000000",
   stroke: "#000000",
   strokeWidth: 1.5,
   cap: "round"
  }
 ]
};

/** What each piece draws, stroke included, in the same 45-unit coordinates. */
export const PIECE_SET_BOXES: Record<string, { x0: number; y0: number; x1: number; y1: number }> = {
 K: {
  x0: 2.75,
  y0: 5.25,
  x1: 42.25,
  y1: 41.25
 },
 Q: {
  x0: 3.25,
  y0: 5.25,
  x1: 41.75,
  y1: 40.25
 },
 R: {
  x0: 8.25,
  y0: 8.25,
  x1: 36.75,
  y1: 39.75
 },
 B: {
  x0: 5.25,
  y0: 4.75,
  x1: 39.75,
  y1: 39.74
 },
 N: {
  x0: 5.25,
  y0: 5.75,
  x1: 39.25,
  y1: 39.75
 },
 P: {
  x0: 10.25,
  y0: 8.25,
  x1: 34.75,
  y1: 40.25
 },
 k: {
  x0: 2.75,
  y0: 5.25,
  x1: 42.25,
  y1: 41.25
 },
 q: {
  x0: 3.25,
  y0: 5.25,
  x1: 41.75,
  y1: 41.84
 },
 r: {
  x0: 8.25,
  y0: 8.25,
  x1: 36.75,
  y1: 39.75
 },
 b: {
  x0: 5.25,
  y0: 4.75,
  x1: 39.75,
  y1: 39.74
 },
 n: {
  x0: 5.25,
  y0: 5.75,
  x1: 39.25,
  y1: 39.75
 },
 p: {
  x0: 10.25,
  y0: 8.25,
  x1: 34.75,
  y1: 40.25
 }
};
